/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Pedido;
import modelo.Producto;
import modelo.Usuario;
import service.Service;

/**
 *
 * @author daw1
 */
public class ProductosComprados extends javax.swing.JFrame {
    private Usuario usuario;   
    private Service services = new Service();
    private Object[][] datos;
    /**
     * Creates new form Productoscomprados
     */
    public ProductosComprados(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        cargarProductosPedidos(services.getPedido(usuario.getIdUsuario()));
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductosPedidos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jcxLimpieza = new javax.swing.JCheckBox();
        jcxRopa = new javax.swing.JCheckBox();
        jcxHerramientas = new javax.swing.JCheckBox();
        jcxAlimentos = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContenido.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        tblProductosPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductosPedidos);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlContenido.add(jPanel1, java.awt.BorderLayout.CENTER);

        jcxLimpieza.setText("Limpieza");
        jcxLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcxLimpiezaActionPerformed(evt);
            }
        });
        jPanel2.add(jcxLimpieza);

        jcxRopa.setText("Ropa");
        jPanel2.add(jcxRopa);

        jcxHerramientas.setText("Herramientas");
        jPanel2.add(jcxHerramientas);

        jcxAlimentos.setText("Alimentos");
        jcxAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcxAlimentosActionPerformed(evt);
            }
        });
        jPanel2.add(jcxAlimentos);

        jButton1.setText("Filtrar");
        jPanel2.add(jButton1);

        pnlContenido.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        lblTitulo.setText("Productos Comprados");
        pnlTitulo.add(lblTitulo);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        btnAceptar.setText("Aceptar");
        pnlBotones.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        pnlBotones.add(btnCancelar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        getAccessibleContext().setAccessibleName("Productos comprados");

        setSize(new java.awt.Dimension(548, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcxLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcxLimpiezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcxLimpiezaActionPerformed

    private void jcxAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcxAlimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcxAlimentosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void cargarProductosPedidos(Pedido p) {
        String[] titulos = {"Nombre", "Vendedor","Precio","Estado","Fecha","Foto"};
        List<Pedido> pedidos = services.getProductoPedido(p.getIdProducto());
        List<Producto> productos = services.getProductos();
        datos = new String[pedidos.size()][6] ;   
   
        for(int i=0; i<pedidos.size(); i++){
           for(Pedido e : services.getPedidos()){   
             if(e.getIdUsuario()==usuario.getIdUsuario()){               
                Producto h = productos.get(pedidos.get(i).getIdProducto());
                datos[i][0] = h.getNombre();
                datos[i][1] = usuario.getNombre();
                datos[i][2] = String.valueOf(h.getPrecio());
                datos[i][3] = String.valueOf(h.getEstado());
                datos[i][4] = String.valueOf(h.getFecha());
                datos[i][5] = String.valueOf(h.getFoto());                
             }
        }
    }
        DefaultTableModel modelo = new DefaultTableModel((Object[][]) datos, titulos);
        tblProductosPedidos.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcxAlimentos;
    private javax.swing.JCheckBox jcxHerramientas;
    private javax.swing.JCheckBox jcxLimpieza;
    private javax.swing.JCheckBox jcxRopa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblProductosPedidos;
    // End of variables declaration//GEN-END:variables
}
