/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;


import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.BorderLayout;
import java.awt.Image;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import modelo.Categoria;
import modelo.Producto;
import modelo.Usuario;
import service.Service;

/**
 *
 * @author daw1
 */
public class ProductosLista extends javax.swing.JFrame {    
    private Usuario usuario;    
    private Categoria categoria;
    private Service services = new Service();
    
    private static final int CONSULTA = 0;
    private static final int MODIFICAR = 1;
    private static final int ALTA = 2;
    
    private int pos;
    
    private int estadoActual;
    
    /**
     * Creates new form ProductosLista
     */
    public ProductosLista(Usuario usuario) {
        
        this.usuario = usuario;  
        initComponents();
        cargarDatos();
        estadoActual=CONSULTA;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        btnSalir = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel7 = new javax.swing.JPanel();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        lblNumeroProducto = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblDescripcion = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblEstado = new javax.swing.JLabel();
        slEstado = new javax.swing.JSlider();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JFormattedTextField();
        lblVendedor = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblFechaString = new javax.swing.JLabel();
        lblFecha = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnConsulta = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbxProducto = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblTitulo.setText("Productos");
        pnlTitulo.add(lblTitulo);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlBotones.setLayout(new java.awt.BorderLayout());

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel8.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel8.add(btnCancelar);
        jPanel8.add(filler2);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel8.add(btnSalir);

        pnlBotones.add(jPanel8, java.awt.BorderLayout.CENTER);
        pnlBotones.add(filler1, java.awt.BorderLayout.PAGE_START);

        btnPrimero.setText("<<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        jPanel7.add(btnPrimero);

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel7.add(btnAnterior);
        jPanel7.add(lblNumeroProducto);

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel7.add(btnSiguiente);

        btnUltimo.setText(">>");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        jPanel7.add(btnUltimo);

        pnlBotones.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlContenido.setLayout(new java.awt.BorderLayout());

        pnlDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 20));
        pnlDatos.setLayout(new java.awt.GridLayout(7, 2, -80, 0));

        lblNombre.setText("Producto");
        pnlDatos.add(lblNombre);

        txtNombre.setEditable(false);
        pnlDatos.add(txtNombre);

        lblCategoria.setText("Categoria");
        pnlDatos.add(lblCategoria);

        cbxCategoria.setEnabled(false);
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });
        pnlDatos.add(cbxCategoria);

        lblDescripcion.setText("Descripcion");
        pnlDatos.add(lblDescripcion);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setName(""); // NOI18N
        jScrollPane2.setViewportView(txtDescripcion);

        jPanel6.add(jScrollPane2);

        pnlDatos.add(jPanel6);

        lblEstado.setText("Estado");
        pnlDatos.add(lblEstado);

        slEstado.setMaximum(5);
        slEstado.setEnabled(false);
        pnlDatos.add(slEstado);

        lblPrecio.setText("Precio");
        pnlDatos.add(lblPrecio);

        txtPrecio.setEditable(false);
        pnlDatos.add(txtPrecio);

        lblVendedor.setText("Vendedor");
        pnlDatos.add(lblVendedor);
        pnlDatos.add(lblUsuario);

        lblFechaString.setText("Fecha");
        pnlDatos.add(lblFechaString);

        lblFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        lblFecha.setToolTipText("");
        lblFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFechaActionPerformed(evt);
            }
        });
        pnlDatos.add(lblFecha);

        pnlContenido.add(pnlDatos, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        jPanel5.add(btnConsulta);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel5.add(btnModificar);

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        jPanel5.add(btnAlta);

        jPanel3.add(jPanel5);

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.add(cbxProducto);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar);

        jPanel4.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        lblImagen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblImagen);

        jPanel4.add(jPanel1, java.awt.BorderLayout.SOUTH);

        pnlContenido.add(jPanel4, java.awt.BorderLayout.WEST);

        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(663, 468));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Volver sin guardar?","Volver",JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION){
            new Principal(usuario).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         if (JOptionPane.showConfirmDialog(this, "¿Quieres cerrar la aplicacion?","Cerrar aplicacion",JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION){
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        mostrarProducto((Producto) cbxProducto.getSelectedItem());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        cambiarEstados(CONSULTA);
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        cambiarEstados(MODIFICAR);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        cambiarEstados(ALTA);
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(estadoActual==ALTA){
        añadirProducto();
        }else if(estadoActual==MODIFICAR){
            modificarProducto();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        mostrarProducto((Producto) cbxProducto.getItemAt(pos+1));
        pos++;
                
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        mostrarProducto((Producto) cbxProducto.getItemAt(pos-1));
        pos--;        
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        mostrarProducto(cbxProducto.getItemAt(0));
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        mostrarProducto(cbxProducto.getItemAt(cbxProducto.getItemCount()-1));
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void lblFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarDatos(){                
        
        for(int i=0;i<services.getProductos().size();i++){
           if(services.getProductos().get(i).getIdUsuario()==usuario.getIdUsuario()){
                 cbxProducto.addItem(services.getProductos().get(i));
                 
            }
        }
        for(int j=0;j<services.getCategorias().size();j++){           
                 cbxCategoria.addItem(services.getCategorias().get(j));            
        }
        
        mostrarProducto((Producto) cbxProducto.getSelectedItem());
    }
    
    private void añadirProducto(){
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe especificarse el Nombre",
                    "Falta Nombre",
                    JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        } else {
            Producto e = new Producto();   
            e.setIdProducto(services.getProductos().size()+1);
            e.setIdCategoria(cbxCategoria.getSelectedIndex());
            e.setIdUsuario(usuario.getIdUsuario());
            e.setNombre(txtNombre.getText());
            //e.setIdCategoria(txtCategoria.get);
            e.setDescripcion(txtDescripcion.getText());            
            e.setEstado(slEstado.getValue());
            e.setFecha((String) lblFecha.getValue());            
            e.setPrecio(Double.valueOf(txtPrecio.getText()));
            e.setFoto(lblImagen.getText());
            services.nuevoProducto(e);
            JOptionPane.showMessageDialog(this, "Evento guardado correctamente");
            
        }
    }
    
   
   private void mostrarProducto(Producto p) {
        txtNombre.setText(String.valueOf(p.getNombre()));        
        txtDescripcion.setText(String.valueOf(p.getDescripcion()));
        cbxCategoria.setSelectedItem(services.getCategoria(p.getIdCategoria()));
        slEstado.setValue(p.getEstado());
        NumberFormat dispFormat = NumberFormat.getCurrencyInstance();
        // Formato de edición: inglés (separador decimal: el punto)
        NumberFormat editFormat = NumberFormat.getNumberInstance(Locale.ENGLISH);
        // Para la edición, no queremos separadores de millares
        editFormat.setGroupingUsed(false);
        // Creamos los formateadores de números
        NumberFormatter dnFormat = new NumberFormatter(dispFormat);
        NumberFormatter enFormat = new NumberFormatter(editFormat);
        // Creamos la factoría de formateadores especificando los
        // formateadores por defecto, de visualización y de edición
        DefaultFormatterFactory currFactory = new DefaultFormatterFactory(dnFormat, dnFormat, enFormat);
        // El formateador de edición admite caracteres incorrectos
        enFormat.setAllowsInvalid(true);
        // Asignamos la factoría al campo
        txtPrecio.setFormatterFactory(currFactory);
        txtPrecio.setValue(p.getPrecio());
        lblUsuario.setText(String.valueOf(services.getUsuario(p.getIdUsuario())));   
        
        lblFecha.setText(p.getFecha());
        
        
        ImageIcon imIc = new ImageIcon("images/productos/" + p.getFoto());
        Image imag = imIc.getImage();
        double max = Math.max(imIc.getIconWidth(), imIc.getIconHeight());
                double fe = 250 / max;
                imag = imag.getScaledInstance(
                        (int) (imIc.getIconWidth() * fe),
                        (int) (imIc.getIconHeight() * fe), Image.SCALE_SMOOTH);
                imIc.setImage(imag);
        lblImagen.setIcon(imIc);
       
    }
   private void consultar(){
       cbxCategoria.setEditable(false);
       txtDescripcion.setEditable(false);
       txtNombre.setEditable(false);
       txtPrecio.setEditable(false);
       cbxProducto.setEnabled(true);
       btnBuscar.setEnabled(true);
       cbxCategoria.setEnabled(false);
       slEstado.setEnabled(false);
   }
   
   private void modificar(){
       JOptionPane.showMessageDialog(this, "Modificar","modificar",JOptionPane.INFORMATION_MESSAGE);
       cbxCategoria.setEnabled(true);
       txtDescripcion.setEditable(true);
       txtNombre.setEditable(true);
       txtPrecio.setEditable(true);
       cbxProducto.setEnabled(false);
       btnBuscar.setEnabled(true);
        slEstado.setEnabled(true);
   }
   private void alta(){
       JOptionPane.showMessageDialog(this, "Alta","Alta",JOptionPane.INFORMATION_MESSAGE);
       modificar();
       cbxProducto.setEnabled(false);
       txtNombre.setText("");        
        txtDescripcion.setText("");
        slEstado.setValue(0);
        txtPrecio.setText("");    
        btnBuscar.setEnabled(false);
        cbxCategoria.setEnabled(true);
        /*slEstado.setValueIsAdjusting(true);*/
        
   }
   
   private void cambiarEstados(int estado){
       
       if(estado==MODIFICAR){
           if(txtDescripcion.getText().isEmpty() ||
                   txtNombre.getText().isEmpty() ||
                   txtPrecio.getText().isEmpty()){
               estado=ALTA;                              
           }else{
                modificar();
               estadoActual=MODIFICAR;
           }                      
       }else if (estado==ALTA){            
           alta();
          estadoActual=ALTA;
       }else if(estado==CONSULTA){           
           consultar();
           JOptionPane.showMessageDialog(this, "Consulta","Consulta",JOptionPane.INFORMATION_MESSAGE);  
           estadoActual=CONSULTA;
       }         
       
       
   }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<Categoria> cbxCategoria;
    private javax.swing.JComboBox<Producto> cbxProducto;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JFormattedTextField lblFecha;
    private javax.swing.JLabel lblFechaString;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JSlider slEstado;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void modificarProducto() {
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe especificarse el Nombre",
                    "Falta Nombre",
                    JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        } else {
            Producto e = (Producto) cbxProducto.getSelectedItem();
            e.setIdProducto(e.getIdProducto());
            e.setIdCategoria(cbxCategoria.getSelectedIndex()+1);
            e.setIdUsuario(e.getIdUsuario());
            e.setNombre(txtNombre.getText());
            //e.setIdCategoria(txtCategoria.get);
            e.setDescripcion(txtDescripcion.getText());            
            e.setEstado(slEstado.getValue());
            e.setFecha(e.getFecha());            
            e.setPrecio((double) txtPrecio.getValue());
            e.setFoto("1p.jpg");
            services.modificarProducto(e);
            JOptionPane.showMessageDialog(this, "Evento guardado correctamente");
            
        }
    }

    
}
