/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author daw1
 */
public class Productoscomprados extends javax.swing.JFrame {

    /**
     * Creates new form Productoscomprados
     */
    public Productoscomprados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jcxLimpieza = new javax.swing.JCheckBox();
        jcxRopa = new javax.swing.JCheckBox();
        jcxHerramientas = new javax.swing.JCheckBox();
        jcxAlimentos = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContenido.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlContenido.add(jPanel1, java.awt.BorderLayout.CENTER);

        jcxLimpieza.setText("Limpieza");
        jcxLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcxLimpiezaActionPerformed(evt);
            }
        });
        jPanel2.add(jcxLimpieza);

        jcxRopa.setText("Ropa");
        jPanel2.add(jcxRopa);

        jcxHerramientas.setText("Herramientas");
        jPanel2.add(jcxHerramientas);

        jcxAlimentos.setText("Alimentos");
        jcxAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcxAlimentosActionPerformed(evt);
            }
        });
        jPanel2.add(jcxAlimentos);

        jButton1.setText("Filtrar");
        jPanel2.add(jButton1);

        pnlContenido.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        lblTitulo.setText("Productos Comprados");
        pnlTitulo.add(lblTitulo);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        btnAceptar.setText("Aceptar");
        pnlBotones.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        pnlBotones.add(btnCancelar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcxLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcxLimpiezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcxLimpiezaActionPerformed

    private void jcxAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcxAlimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcxAlimentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productoscomprados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productoscomprados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productoscomprados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productoscomprados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productoscomprados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox jcxAlimentos;
    private javax.swing.JCheckBox jcxHerramientas;
    private javax.swing.JCheckBox jcxLimpieza;
    private javax.swing.JCheckBox jcxRopa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables
}
