/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;


import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.Categoria;
import modelo.Producto;
import modelo.Usuario;
import service.Service;

/**
 *
 * @author daw1
 */
public class ProductosLista extends javax.swing.JFrame {    
    private Usuario usuario;    

    private Service services = new Service();
    private File f;
    
    private static final int CONSULTA = 0;
    private static final int MODIFICAR = 1;
    private static final int ALTA = 2;
    
    private int pos;
    
    private int estadoActual;
    
    /**
     * Creates new form ProductosLista
     */
    public ProductosLista(Usuario usuario) {
        
        this.usuario = usuario; 
        
        initComponents();
        cargarDatos();
        cambiarEstados(CONSULTA);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        btnSalir = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel7 = new javax.swing.JPanel();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        lblNumeroProducto = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblDescripcion = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblEstado = new javax.swing.JLabel();
        slEstado = new javax.swing.JSlider();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JFormattedTextField();
        lblVendedor = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblFechaString = new javax.swing.JLabel();
        lblFecha = new javax.swing.JFormattedTextField();
        btnEliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnConsulta = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbxProducto = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmEstado = new javax.swing.JMenu();
        jmConsulta = new javax.swing.JMenu();
        miBuscar = new javax.swing.JMenuItem();
        jmModificar = new javax.swing.JMenu();
        miAceptarModificar = new javax.swing.JMenuItem();
        jmAlta = new javax.swing.JMenu();
        miAceptarAlta = new javax.swing.JMenuItem();
        jmMover = new javax.swing.JMenu();
        miSiguiente = new javax.swing.JMenuItem();
        miAnterior = new javax.swing.JMenuItem();
        miPrimero = new javax.swing.JMenuItem();
        miUltimo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblTitulo.setText("Productos");
        pnlTitulo.add(lblTitulo);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlBotones.setLayout(new java.awt.BorderLayout());

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel8.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel8.add(btnCancelar);
        jPanel8.add(filler2);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel8.add(btnSalir);

        pnlBotones.add(jPanel8, java.awt.BorderLayout.CENTER);
        pnlBotones.add(filler1, java.awt.BorderLayout.PAGE_START);

        btnPrimero.setText("<<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        jPanel7.add(btnPrimero);

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel7.add(btnAnterior);
        jPanel7.add(lblNumeroProducto);

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel7.add(btnSiguiente);

        btnUltimo.setText(">>");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        jPanel7.add(btnUltimo);

        pnlBotones.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlContenido.setLayout(new java.awt.BorderLayout());

        pnlDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 20));
        pnlDatos.setLayout(new java.awt.GridBagLayout());

        lblNombre.setText("Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        pnlDatos.add(lblNombre, gridBagConstraints);

        txtNombre.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.weightx = 0.6;
        pnlDatos.add(txtNombre, gridBagConstraints);

        lblCategoria.setText("Categoria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        pnlDatos.add(lblCategoria, gridBagConstraints);

        cbxCategoria.setEnabled(false);
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.weightx = 0.5;
        pnlDatos.add(cbxCategoria, gridBagConstraints);

        lblDescripcion.setText("Descripcion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        pnlDatos.add(lblDescripcion, gridBagConstraints);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setName(""); // NOI18N
        jScrollPane2.setViewportView(txtDescripcion);

        jPanel6.add(jScrollPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 0.6;
        pnlDatos.add(jPanel6, gridBagConstraints);

        lblEstado.setText("Estado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        pnlDatos.add(lblEstado, gridBagConstraints);

        slEstado.setMajorTickSpacing(1);
        slEstado.setMaximum(5);
        slEstado.setMinimum(1);
        slEstado.setMinorTickSpacing(1);
        slEstado.setPaintLabels(true);
        slEstado.setPaintTicks(true);
        slEstado.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.8;
        pnlDatos.add(slEstado, gridBagConstraints);
        slEstado.getAccessibleContext().setAccessibleName("Productos");

        lblPrecio.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        pnlDatos.add(lblPrecio, gridBagConstraints);

        txtPrecio.setEditable(false);
        txtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.weightx = 0.8;
        pnlDatos.add(txtPrecio, gridBagConstraints);

        lblVendedor.setText("Vendedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        pnlDatos.add(lblVendedor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.8;
        pnlDatos.add(lblUsuario, gridBagConstraints);

        lblFechaString.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        pnlDatos.add(lblFechaString, gridBagConstraints);

        lblFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        lblFecha.setToolTipText("");
        lblFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFechaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.weightx = 0.8;
        pnlDatos.add(lblFecha, gridBagConstraints);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlDatos.add(btnEliminar, gridBagConstraints);

        pnlContenido.add(pnlDatos, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        jPanel5.add(btnConsulta);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel5.add(btnModificar);

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        jPanel5.add(btnAlta);

        jPanel3.add(jPanel5);

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.add(cbxProducto);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar);

        jPanel4.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        lblImagen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen);

        jPanel4.add(jPanel1, java.awt.BorderLayout.SOUTH);

        pnlContenido.add(jPanel4, java.awt.BorderLayout.WEST);

        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        jmEstado.setText("Estados");

        jmConsulta.setText("Consulta");
        jmConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmConsultaMouseClicked(evt);
            }
        });
        jmConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaActionPerformed(evt);
            }
        });

        miBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        miBuscar.setText("Bucar");
        jmConsulta.add(miBuscar);

        jmEstado.add(jmConsulta);

        jmModificar.setText("Modificar");
        jmModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmModificarMouseClicked(evt);
            }
        });
        jmModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarActionPerformed(evt);
            }
        });

        miAceptarModificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        miAceptarModificar.setText("Aceptar");
        miAceptarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAceptarModificarActionPerformed(evt);
            }
        });
        jmModificar.add(miAceptarModificar);

        jmEstado.add(jmModificar);

        jmAlta.setText("Alta");
        jmAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAltaMouseClicked(evt);
            }
        });
        jmAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAltaActionPerformed(evt);
            }
        });

        miAceptarAlta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        miAceptarAlta.setText("Aceptar");
        miAceptarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAceptarAltaActionPerformed(evt);
            }
        });
        jmAlta.add(miAceptarAlta);

        jmEstado.add(jmAlta);

        jMenuBar1.add(jmEstado);

        jmMover.setText("Mover");
        jmMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMoverActionPerformed(evt);
            }
        });

        miSiguiente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, 0));
        miSiguiente.setText("Siguiente");
        miSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSiguienteActionPerformed(evt);
            }
        });
        jmMover.add(miSiguiente);

        miAnterior.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, 0));
        miAnterior.setText("Anterior");
        miAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnteriorActionPerformed(evt);
            }
        });
        jmMover.add(miAnterior);

        miPrimero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_MASK));
        miPrimero.setText("Primero");
        miPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrimeroActionPerformed(evt);
            }
        });
        jmMover.add(miPrimero);

        miUltimo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.CTRL_MASK));
        miUltimo.setText("Ultimo");
        miUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUltimoActionPerformed(evt);
            }
        });
        jmMover.add(miUltimo);

        jMenuBar1.add(jmMover);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(679, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Volver sin guardar?","Volver",JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION){
            new Principal(usuario).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         if (JOptionPane.showConfirmDialog(this, "¿Quieres cerrar la aplicacion?","Cerrar aplicacion",JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION){
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        mostrarProducto((Producto) cbxProducto.getSelectedItem());        
        pos=cbxProducto.getSelectedIndex();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        cambiarEstados(CONSULTA);
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        cambiarEstados(MODIFICAR);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        cambiarEstados(ALTA);
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(estadoActual==ALTA){
        añadirProducto();
        }else if(estadoActual==MODIFICAR){
            modificarProducto();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if(pos<cbxProducto.getItemCount()-1){
        mostrarProducto((Producto) cbxProducto.getItemAt(pos+1));        
        pos++;
        cbxProducto.setSelectedItem(pos);
        }else{
        }
                
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if(pos>0){
        mostrarProducto((Producto) cbxProducto.getItemAt(pos-1));        
        pos--; 
        cbxProducto.setSelectedItem(cbxProducto.getItemAt(pos));
        }       
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        mostrarProducto(cbxProducto.getItemAt(0));
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        mostrarProducto(cbxProducto.getItemAt(cbxProducto.getItemCount()-1));
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void lblFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechaActionPerformed

    private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked
        if(estadoActual==ALTA || estadoActual==MODIFICAR){
        JFileChooser jfc = new JFileChooser();
        jfc.setMultiSelectionEnabled(false);
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileFilter filter = new FileNameExtensionFilter("JPEG (*.jpeg,*.jpg)", "jpg", "jpeg");
        jfc.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("PNG (*.png)", "png");
        jfc.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("GIF (*.gif)", "gif");
        jfc.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("Todas las imágenes", "gif","png","jpg","jpeg","bmp");
        jfc.addChoosableFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
            File fd = new File(f.getName());
            try {
                BufferedInputStream bis = new BufferedInputStream(
                        new FileInputStream(f));
                BufferedOutputStream bos = new BufferedOutputStream(
                        new FileOutputStream(fd));
                if(!f.equals(fd)){
                int c;
                while ((c = bis.read()) != -1) {
                    bos.write(c);
                }
                bos.flush();
                bos.close();
                bis.close();
                ImageIcon imIc = new ImageIcon(f.getName());
                Image imag = imIc.getImage();
               
                int max = Math.max(imIc.getIconWidth(), imIc.getIconHeight());
                double fe = 250 / max;
                imag = imag.getScaledInstance(
                        (int) (imIc.getIconWidth() * fe),
                        (int) (imIc.getIconHeight() * fe), Image.SCALE_SMOOTH);
                imIc.setImage(imag);
                lblImagen.setIcon(imIc);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ProductosLista.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ProductosLista.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_lblImagenMouseClicked

    private void miAceptarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAceptarModificarActionPerformed
        if(estadoActual==ALTA){
        añadirProducto();
        }else if(estadoActual==MODIFICAR){
            modificarProducto();
        }
    }//GEN-LAST:event_miAceptarModificarActionPerformed

    private void miAceptarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAceptarAltaActionPerformed
        if(estadoActual==ALTA){
        añadirProducto();
        }else if(estadoActual==MODIFICAR){
            modificarProducto();
        }
    }//GEN-LAST:event_miAceptarAltaActionPerformed

    private void miUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUltimoActionPerformed
        
        mostrarProducto(cbxProducto.getItemAt(cbxProducto.getItemCount()-1));
        pos=cbxProducto.getItemCount()-1;
        cbxProducto.setSelectedItem(pos);
    }//GEN-LAST:event_miUltimoActionPerformed

    private void miSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSiguienteActionPerformed
        if(pos<cbxProducto.getItemCount()-1){
        mostrarProducto((Producto) cbxProducto.getItemAt(pos+1));        
        pos++;
        cbxProducto.setSelectedItem(pos);
        }else{
        }
    }//GEN-LAST:event_miSiguienteActionPerformed

    private void miAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnteriorActionPerformed
        if(pos>0){
        mostrarProducto((Producto) cbxProducto.getItemAt(pos-1));        
        pos--; 
        cbxProducto.setSelectedItem(pos);
        }
    }//GEN-LAST:event_miAnteriorActionPerformed

    private void miPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrimeroActionPerformed
        mostrarProducto(cbxProducto.getItemAt(0));
        pos=0;
        cbxProducto.setSelectedItem(pos);
    }//GEN-LAST:event_miPrimeroActionPerformed

    private void jmMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmMoverActionPerformed

    private void jmAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAltaActionPerformed
        
    }//GEN-LAST:event_jmAltaActionPerformed

    private void jmModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarActionPerformed
       
    }//GEN-LAST:event_jmModificarActionPerformed

    private void jmConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaActionPerformed
        
    }//GEN-LAST:event_jmConsultaActionPerformed

    private void jmConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmConsultaMouseClicked
        cambiarEstados(CONSULTA);
    }//GEN-LAST:event_jmConsultaMouseClicked

    private void jmModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmModificarMouseClicked
        cambiarEstados(MODIFICAR);
    }//GEN-LAST:event_jmModificarMouseClicked

    private void jmAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAltaMouseClicked
        cambiarEstados(ALTA);
    }//GEN-LAST:event_jmAltaMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Quieres eliminar el producto?","eliminar producto",JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION){
            eliminarProducto();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarDatos(){                
        
        for(int i=0;i<services.getProductos().size();i++){
           if(services.getProductos().get(i).getIdUsuario()==usuario.getIdUsuario()){
                 cbxProducto.addItem(services.getProductos().get(i));
                 
            }
        }
        for(int j=0;j<services.getCategorias().size();j++){           
                 cbxCategoria.addItem(services.getCategorias().get(j));            
        }
        if(cbxProducto.getItemCount()!=0){
        mostrarProducto((Producto) cbxProducto.getSelectedItem());
        }else{
            cambiarEstados(ALTA);
        }
    }
    
    private void eliminarProducto(){
        Producto p = new Producto();
        p = (Producto) cbxProducto.getSelectedItem();
        
        services.eliminarProducto(p);
        if(cbxProducto.getItemCount()!=0){
        mostrarProducto(cbxProducto.getItemAt(cbxProducto.getSelectedIndex()+1));
        }else{
            cambiarEstados(ALTA);
        }
    }
    
    private void añadirProducto(){
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe especificarse el Nombre",
                    "Falta Nombre",
                    JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        } else {
            Producto e = new Producto();   
            int max = 0;
            for(Producto p : services.getProductos()){                
                if(max<p.getIdProducto())
			{                            
                            max=p.getIdProducto();
			}
            }
            e.setIdProducto(max+1);
            e.setIdCategoria(cbxCategoria.getSelectedIndex());
            e.setIdUsuario(usuario.getIdUsuario());
            e.setNombre(txtNombre.getText());
            //e.setIdCategoria(txtCategoria.get);
            e.setDescripcion(txtDescripcion.getText());            
            e.setEstado(slEstado.getValue());
            e.setFecha((Date) lblFecha.getValue());            
            e.setPrecio(Double.valueOf(String.valueOf(txtPrecio.getValue())));
            e.setFoto(String.valueOf(lblImagen.getIcon()));
            services.nuevoProducto(e);
            JOptionPane.showMessageDialog(this, "Evento guardado correctamente");
            
        }
    }
    
   
   private void mostrarProducto(Producto p) {
       
        cbxProducto.setSelectedItem(p);
        txtNombre.setText(String.valueOf(p.getNombre()));        
        txtDescripcion.setText(String.valueOf(p.getDescripcion()));
        cbxCategoria.setSelectedItem(services.getCategoria(p.getIdCategoria()));
        slEstado.setValue(p.getEstado());
       
        txtPrecio.setValue(p.getPrecio());
        lblUsuario.setText(String.valueOf(services.getUsuario(p.getIdUsuario())));   
        
        lblFecha.setValue(p.getFecha());
        
        ImageIcon defecto = new ImageIcon("images/productos/defecto.jpg");
        ImageIcon imIc = new ImageIcon("images/productos/" + p.getFoto());
        Image imag = imIc.getImage();
        double max = Math.max(imIc.getIconWidth(), imIc.getIconHeight());
                double fe = 250 / max;
                imag = imag.getScaledInstance(
                        (int) (imIc.getIconWidth() * fe),
                        (int) (imIc.getIconHeight() * fe), Image.SCALE_SMOOTH);
                imIc.setImage(imag);
                defecto.setImage(imag);                        
            lblImagen.setIcon(imIc);        
        
       
       
    }
   private void consultar(){
       cbxCategoria.setEditable(false);
       txtDescripcion.setEditable(false);
       txtNombre.setEditable(false);
       txtPrecio.setEditable(false);
       cbxProducto.setEnabled(true);
       btnBuscar.setEnabled(true);
       cbxCategoria.setEnabled(false);
       slEstado.setEnabled(false);
       miBuscar.setEnabled(true);
       miAceptarAlta.setEnabled(false);
       miAceptarModificar.setEnabled(false);
       miAnterior.setEnabled(true);
       miSiguiente.setEnabled(true);
       miPrimero.setEnabled(true);
       miUltimo.setEnabled(true);
       btnEliminar.setEnabled(false);
   }
   
   private void modificar(){
      
       cbxCategoria.setEnabled(true);
       txtDescripcion.setEditable(true);
       txtNombre.setEditable(true);
       txtPrecio.setEditable(true);
       cbxProducto.setEnabled(false);
       btnBuscar.setEnabled(true);
        slEstado.setEnabled(true);
        miBuscar.setEnabled(false);
       miAceptarAlta.setEnabled(true);
       miAceptarModificar.setEnabled(true);
       miAnterior.setEnabled(false);
       miSiguiente.setEnabled(false);
       miPrimero.setEnabled(false);
       miUltimo.setEnabled(false);
       btnPrimero.setEnabled(false);
       btnAnterior.setEnabled(false);
       btnSiguiente.setEnabled(false);
       btnUltimo.setEnabled(false);
       btnEliminar.setEnabled(true);
       btnBuscar.setEnabled(false);
       
   }
   private void alta(){
       modificar();
       cbxProducto.setEnabled(false);
       txtNombre.setText("");        
        txtDescripcion.setText("");
        ImageIcon defecto = new ImageIcon("images/productos/defecto.jpg");
        lblImagen.setIcon(defecto);
        slEstado.setValue(0);
        txtPrecio.setText("");    
        btnBuscar.setEnabled(false);
        cbxCategoria.setEnabled(true);      
       miAceptarModificar.setEnabled(false);
       btnEliminar.setEnabled(false);
       btnBuscar.setEnabled(false);
        /*slEstado.setValueIsAdjusting(true);*/
        
   }
   
   private void cambiarEstados(int estado){
       
       if(estado==MODIFICAR){
           if(txtDescripcion.getText().isEmpty() ||
                   txtNombre.getText().isEmpty() ||
                   txtPrecio.getText().isEmpty()){
               estado=ALTA;                              
           }else{
                modificar();
                JOptionPane.showMessageDialog(this, "Modificar","modificar",JOptionPane.INFORMATION_MESSAGE);  
               estadoActual=MODIFICAR;
           }                      
       }else if (estado==ALTA){            
           alta();
          estadoActual=ALTA;
       }else if(estado==CONSULTA){           
           consultar();
           
           estadoActual=CONSULTA;
       }         
       
       
   }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<Categoria> cbxCategoria;
    private javax.swing.JComboBox<Producto> cbxProducto;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu jmAlta;
    private javax.swing.JMenu jmConsulta;
    private javax.swing.JMenu jmEstado;
    private javax.swing.JMenu jmModificar;
    private javax.swing.JMenu jmMover;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JFormattedTextField lblFecha;
    private javax.swing.JLabel lblFechaString;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JMenuItem miAceptarAlta;
    private javax.swing.JMenuItem miAceptarModificar;
    private javax.swing.JMenuItem miAnterior;
    private javax.swing.JMenuItem miBuscar;
    private javax.swing.JMenuItem miPrimero;
    private javax.swing.JMenuItem miSiguiente;
    private javax.swing.JMenuItem miUltimo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JSlider slEstado;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void modificarProducto() {
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe especificarse el Nombre",
                    "Falta Nombre",
                    JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        } else {
            Producto e = (Producto) cbxProducto.getSelectedItem();
            e.setIdProducto(e.getIdProducto());
            e.setIdCategoria(cbxCategoria.getSelectedIndex()+1);
            e.setIdUsuario(e.getIdUsuario());
            e.setNombre(txtNombre.getText());
            //e.setIdCategoria(txtCategoria.get);
            e.setDescripcion(txtDescripcion.getText());            
            e.setEstado(slEstado.getValue());
            e.setFecha((Date) lblFecha.getValue());            
            e.setPrecio(Double.valueOf(String.valueOf(txtPrecio.getValue())));
            
            e.setFoto(String.valueOf(lblImagen.getIcon()));
            services.modificarProducto(e);
            JOptionPane.showMessageDialog(this, "Evento guardado correctamente");
            
        }
    }

    
}
