/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.UsuarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Usuario;
import service.Service;
import util.SHA;

/**
 *
 * @author daw1
 */
public class Registro extends javax.swing.JFrame {
    private Service services = new Service();
    
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();
        lblNick = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        pwdContraseña = new javax.swing.JPasswordField();
        lblRContraseña = new javax.swing.JLabel();
        pwdRContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Resgistro");
        pnlTitulo.add(jLabel2);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlContenido.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 20, 100, 20));
        pnlContenido.setLayout(new java.awt.GridLayout(5, 2, -60, 20));

        lblNick.setText("Apodo");
        pnlContenido.add(lblNick);
        pnlContenido.add(txtNick);

        lblNombre.setText("Nombre: ");
        pnlContenido.add(lblNombre);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        pnlContenido.add(txtNombre);

        lblApellido.setText("Apellido");
        pnlContenido.add(lblApellido);
        pnlContenido.add(txtApellido);

        lblContraseña.setText("Contraseña");
        pnlContenido.add(lblContraseña);

        pwdContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdContraseñaActionPerformed(evt);
            }
        });
        pnlContenido.add(pwdContraseña);

        lblRContraseña.setText("Confirmar contraseña");
        pnlContenido.add(lblRContraseña);
        pnlContenido.add(pwdRContraseña);

        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 473));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void pwdContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdContraseñaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        registrarse();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
        
    }
    
    private void registrarse(){
        
        String nick;
        String nombre;
        String apellido;
        String contraseña;
        String rContraseña;
        
        nick = txtNick.getText();
        nombre = txtNombre.getText() ;
        apellido = txtApellido.getText();
        contraseña = new String (pwdContraseña.getPassword());
        rContraseña = new String (pwdRContraseña.getPassword());
        
        if (nombre.isEmpty() || apellido.isEmpty() || nick.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe especificarse el usuario",
                    "Faltan datos",
                    JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        } else if (pwdContraseña.getPassword().length == 0 || pwdRContraseña.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe especificarse la contraseña",
                    "Faltan datos",
                    JOptionPane.ERROR_MESSAGE);
            pwdContraseña.requestFocus();
        }else if (!contraseña.equals(rContraseña)){
            JOptionPane.showMessageDialog(this, "Las contraseñas con coinciden","Error",JOptionPane.ERROR_MESSAGE);
        }else {
            
            Usuario u = services.registro(txtNick.getText(), contraseña);
            if (u == null) {
                u = new Usuario();
                u.setIdUsuario(services.getUsuarios().size()+1);
                u.setNick(nick);
                u.setNombre(nombre);
                u.setApellido(apellido);
                u.setPassword(contraseña);
                u.setSalto(SHA.getSalt());
                u.setFoto(services.getUsuarios().size()+1 + ".png");
                
                services.nuevoUsuario(u, contraseña);
                JOptionPane.showMessageDialog(this, "Usuario creado correctamente","Confirmacion",JOptionPane.INFORMATION_MESSAGE);
                new Login().setVisible(true);
                this.dispose();
                
            } else {
                /*new MainForm(u);*/
                JOptionPane.showMessageDialog(this, "Este usuario ya existe");
                txtNombre.requestFocus();
            }
        }
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNick;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRContraseña;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPasswordField pwdContraseña;
    private javax.swing.JPasswordField pwdRContraseña;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNick;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
